name: CraftWorlds
main: me.furt.craftworlds.CraftWorlds
version: 0.3
author: furt
description: A plugin that supports multiworld creation, teleport, and load.
commands:
  world:
    description: World commands
    usage: |
           /<command> [create:list:port]