name: CraftWorlds
main: me.furt.craftworlds.CraftWorlds
version: 2.0
author: furt
database: true
description: A plugin that supports multiworld creation, teleport, and load.
commands:
  world:
    aliases:
      - cw
    description: World commands
    usage: |
           /<command> [create] <world> <environment> <seed>
           /<command> [delete] <world>
           /<command> [list]
           /<command> [port] <world>
           /<command> [set] <world> [pvp]
           /<command> [set] <world> [toggle]