name: CraftWorlds
main: me.furt.craftworlds.CraftWorlds
version: 1.0
author: furt
database: true
description: A plugin that supports multiworld creation, teleport, and load.
commands:
  world:
    description: World commands
    usage: |
           /<command> [create] <world> <environment> <seed>
           /<command> [delete] <world>
           /<command> [list]
           /<command> [port] <world>
           /<command> [set] <world> [pvp]
           /<command> [set] <world> [toggle]
  weather:
    description: Weather commands
    usage: |
           /<command> [storm]
           /<command> [duration]
           /<command> [thunder] <duration>
           /<command> [strike]
           /<command> [strike] <player>